In [1]:
import numpy as np #导入numpy库
a = np.array([1,2,3,4]) #创建一个数据a
print(a)
print(a.shape)
# [1 2 3 4]

import time #导入时间库
a = np.random.rand(1000000) # （1000000,）的一维数组
print(a.shape)
b = np.random.rand(1000000) #通过round随机得到两个一百万维度的数组
tic = time.time() #现在测量一下当前时间

#向量化的版本
c = np.dot(a,b) # 通过np.dot函数计算两个向量的点积
print(c.shape)
toc = time.time()
print("Vectorized version:" + str(1000*(toc-tic)) +"ms") #打印一下向量化的版本的时间

#继续增加非向量化的版本
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print("For loop:" + str(1000*(toc-tic)) + "ms")#打印for循环的版本的时间

[1 2 3 4]
(4,)
(1000000,)
()
Vectorized version:0.4982948303222656ms
For loop:280.61962127685547ms


In [2]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]]) #创建一个3*4的矩阵

cal = A.sum(axis = 0) # 按行合并，即按列求和，得到 1*4 的矩阵
percentage = 100 * A / cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
